name: Secrets Smoke Test
on:
  workflow_dispatch:

jobs:
  verify-secrets:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Verify PQC Secrets availability
        run: |
          echo "✅ Checking secret availability (values are masked)..."
          if [ -z "${{ secrets.PQC_KEY_VERSION }}" ]; then
            echo "❌ PQC_KEY_VERSION not found!" && exit 1
          fi
          if [ -z "${{ secrets.MLKEM_PUBLIC_KEY_B64 }}" ]; then
            echo "❌ MLKEM_PUBLIC_KEY_B64 not found!" && exit 1
          fi
          if [ -z "${{ secrets.MLKEM_PRIVATE_KEY_KMS_URI }}" ]; then
            echo "❌ MLKEM_PRIVATE_KEY_KMS_URI not found!" && exit 1
          fi
          if [ -z "${{ secrets.MLKEM_KAT_TARBALL_B64 }}" ]; then
            echo "❌ MLKEM_KAT_TARBALL_B64 not found!" && exit 1
          fi
          echo "✅ All secrets exist and are accessible in CI."
